version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: db_cake
    environment: 
      - POSTGRES_DB=cake_shop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80  

  mysql:
    image: mysql:5
    environment: 
      - MYSQL_DATABASE=cake_shop
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PORT=3306
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
